#!/usr/bin/env bash
# Regenerates internal/tz/zones_data.go from the system zoneinfo database.
# Run this after a tzdata update: scripts/gen-zones.sh
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="${REPO_ROOT}/internal/tz/zones_data.go"

# Resolve the real zoneinfo root (macOS uses a symlink)
for candidate in /usr/share/zoneinfo /usr/share/lib/zoneinfo /var/db/timezone/zoneinfo; do
    if [ -d "$candidate/Africa" ]; then
        ZONEROOT="$candidate"
        break
    fi
done

if [ -z "${ZONEROOT:-}" ]; then
    echo "error: could not find a zoneinfo directory" >&2
    exit 1
fi

VERSION=$(cat "${ZONEROOT}/+VERSION" 2>/dev/null || echo "unknown")

echo "Using zoneinfo at ${ZONEROOT} (${VERSION})"

# Collect all Region/City entries, skip posix/ and right/ duplicates
ZONES=$(find \
    "${ZONEROOT}/Africa" \
    "${ZONEROOT}/America" \
    "${ZONEROOT}/Antarctica" \
    "${ZONEROOT}/Arctic" \
    "${ZONEROOT}/Asia" \
    "${ZONEROOT}/Atlantic" \
    "${ZONEROOT}/Australia" \
    "${ZONEROOT}/Etc" \
    "${ZONEROOT}/Europe" \
    "${ZONEROOT}/Indian" \
    "${ZONEROOT}/Pacific" \
    -type f 2>/dev/null \
    | sed "s|${ZONEROOT}/||" \
    | sort)

COUNT=$(echo "$ZONES" | wc -l | tr -d ' ')
echo "Found ${COUNT} zones"

{
    echo "// Code generated by scripts/gen-zones.sh; DO NOT EDIT."
    echo "package tz"
    echo ""
    echo "// ianaZones is the complete list of IANA timezone names from tzdata ${VERSION}."
    echo "var ianaZones = []string{"
    echo "$ZONES" | while IFS= read -r zone; do
        echo "	\"${zone}\","
    done
    echo "}"
} > "$OUT"

echo "Written to ${OUT}"
